name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          
# Vérification de la présence du fichier index.html
      - name: Vérifier la présence de index.html
        run: |
          if [ -f "./todo-app/src/frontend/index.html" ]; then
            echo "Le fichier index.html existe."
          else
            echo "Erreur : index.html n’existe pas!"
            exit 1
          fi
          
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_SKY_092F30A03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./todo-app/src/frontend" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "." # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

          # Analyse des performances avec Lighthouse
      - name: Exécuter Lighthouse sur le build
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: ${{ steps.builddeploy.outputs.static_web_app_url }}
          uploadArtifacts: true # Sauvegarde les résultats du rapport
          temporaryPublicStorage: true # Génère un lien public vers le rapport

      - name: Exécuter Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: "https://todoapp.nathanwitz.emf-informatique.ch/" # Remplace par l'URL de ton app déployée
          configPath: ".lighthouserc.json" # Facultatif, pour configurer Lighthouse
          uploadArtifacts: false # Pour voir les rapports dans GitHub Actions
          temporaryPublicStorage: true # Partage temporaire des rapports

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_SKY_092F30A03 }}
          action: "close"
