name: CI Workflow

on:
  push:
    branches:
      - main  # Tu peux changer cette branche si c'est une autre que 'main'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Ou une version spécifique si c'est le cas

      - name: Install dependencies
        run: npm install  # Si tu utilises npm pour installer les dépendances

      - name: Run tests
        run: npm test  # Si tu as des tests à lancer, ajuste selon ton projet
